version: '3'

services:
  application:
    restart: always
    build: .
    ports:
      - '5880:80'
      - '58443:443'
    volumes:
      - web-root:/var/www/html
      - ./.nginx:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    networks:
      - app-network
  certbot:
    image: certbot/certbot
    depends_on:
      - application
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email alexbidenko1998@gmail.com --agree-tos --no-eff-email --staging -d trello.admire.social  -d www.trello.admire.social

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/alexbidenko/admire_trello/views/
      o: bind

networks:
  app-network:
    driver: bridge
