version: '3'

services:
  application:
    restart: always
    build: .
    ports:
      - '5880:80'
      - '58443:443'
    volumes:
      - web-root:/var/www/html
      - ./.nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - app-network
  certbot:
    image: certbot/certbot
    depends_on:
      - application
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - web-root:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email alexbidenko1998@gmail.com --agree-tos --no-eff-email --staging -d trello.admire.social  -d www.trello.admire.social
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
